<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
    <Folder Include="Domain-Interfaces\" />
    <Folder Include="Domain-Entities\" />
    <Folder Include="Domain-ValueObjects\" />
    <Folder Include="Application\" />
    <Folder Include="Application-Repositories\" />
  </ItemGroup>

</Project>
